language: java
jdk: openjdk11
services:
  - xvfb
cache:
  directories:
    - $home/.m2
before_install:
  - sudo apt-get update
  - sudo apt-get install matchbox-window-manager
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - Xvfb :10 -ac -screen 0 1280x1024x24
  - DISPLAY=:10 matchbox-window-manager
install: true
script:
  - mvn clean test
