language: java
matrix:
  include:
    # Headed Linux
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - --add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
services:
  - xvfb
cache:
  directories:
    - $home/.m2
install: true
script:
  - xvfb-run --server-args="-screen 0 1024x768x24" mvn clean test
