language: java
jdk: openjdk11
services:
  - xvfb
cache:
  directories:
    - $home/.m2
before_install:
  - sudo apt-get update
  - sudo apt-get install matchbox-window-manager
  - export DISPLAY=:99.0
  - DISPLAY=:10 matchbox-window-manager
  - sh -e /etc/init.d/xvfb start
install: true
script:
  - mvn clean test
