version: '2.1'
orbs:
  maven: circleci/maven@1.1

commands:
  maven_package:
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                command: |-
                  #!/bin/bash
                  
                  set -x
                  # shellcheck disable=SC2086
                  mvn clean package "$@"
                  set +x
                name: Package Contents Using Maven
      - maven/process_test_results
  install_wix:
    steps:
      - run:
          command: |-
            cd ..
            mkdir dotnet
            cd dotnet
            wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
            chmod +x ./dotnet-install.sh
            ./dotnet-install.sh --version latest
            export DOTNET_ROOT=$HOME/.dotnet
            export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
            dotnet tool install --global wix
          name: Install WiX
  create_msi:
    steps:
      - run:
          command: |-
            jpackage --input ./target --dest ./installer --name "Desktop Finance" --main-jar desktop-finance.jar --main-class com.andrewhun.finance.App --type "msi"
          name: Create MSI
  git_commit:
    steps:
      - run:
          command: |-
            #!/bin/bash
            git config --global user.email "andrewhun995@gmail.com"
            git config --global user.name "Andras Tyichi"
            git branch -u origin/reset
            git add --all
            git commit -m "Pushing Packaged Content Via CircleCI [skip ci]"
            git push
          name: Commit to Git

jobs:
  package_and_commit:
    executor:
      name: maven/default
      tag: "21.0.0-node"
    steps:
      - maven_package
      - install_wix
      - create_msi
      - git_commit


workflows:
  package_and_commit:
    jobs:
      - package_and_commit