version: '2.1'
orbs:
  maven: circleci/maven@1.1

commands:
  maven_package:
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                command: |-
                  #!/bin/bash
                  
                  set -x
                  # shellcheck disable=SC2086
                  mvn clean package "$@"
                  set +x
                name: Package Contents Using Maven
      - maven/process_test_results
  install_wix:
    steps:
      - run:
          command: |-
            cd ..
            mkdir dotnet
            cd dotnet
            wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
            chmod +x ./dotnet-install.sh
            ./dotnet-install.sh --version latest
            export DOTNET_ROOT=$HOME/.dotnet
            export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
            dotnet tool install --global wix
          name: Install WiX
  create_msi:
    steps:
      - run:
          command: |-
            jpackage --input ./target --dest ./installer --name "Desktop Finance" --main-jar desktop-finance.jar --main-class com.andrewhun.finance.App --type "msi" --verbose
          name: Create MSI
  generate_executable:
    steps:
      - run:
          command: |-
            cd installer
            mkdir launch4j-temp
            cd launch4j-temp
            wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz
            tar -xf launch4j-3.50-linux-x64.tgz
            cd launch4j
            wget https://builds.openlogic.com/downloadJDK/openlogic-openjdk-jre/21.0.3+9/openlogic-openjdk-jre-21.0.3+9-linux-x64.tar.gz
            tar -xf openlogic-openjdk-jre-21.0.3+9-linux-x64.tar.gz
            mv ./openlogic-openjdk-jre-21.0.3+9-linux-x64 ./jre
            cp ../../../target/desktop-finance-jar-with-dependencies.jar ./
            cp ../../launch4j-config.xml ./
            sed -i -e 's/\r$//' ./launch4j
            ./launch4j launch4j-config.xml
            cd ../..
            cp launch4j-temp/launch4j/desktop-finance-nsis.exe ./
            rm -rf launch4j-temp
            rm desktop-finance-nsis.exe
          name: Generate Executable Using Launch4j
  generate_installer:
    steps:
      - run:
          command: |-
            cd installer
            mkdir nsis-temp
            cd nsis-temp
            wget https://sourceforge.net/projects/nsis/files/NSIS%203/3.10/nsis-3.10-src.tar.bz2
            tar -xf nsis-3.10-src.tar.bz2
            cd nsis-3.10-src
            wget http://prdownloads.sourceforge.net/scons/scons-local-4.8.0.tar.gz
            tar -xf scons-local-4.8.0.tar.gz
            scons-local-4.8.0/scons
            cp ../../desktop-finance-installer-script.nsi ./
            ls
            cd ../..
            rm -rf nsis-temp
            ls
          name: Generate Installer Using NSIS
  git_commit:
    steps:
      - run:
          command: |-
            #!/bin/bash
            git config --global user.email "andrewhun995@gmail.com"
            git config --global user.name "Andras Tyichi"
            git branch -u origin/reset
            git add --all
            git commit -m "Pushing Packaged Content Via CircleCI [skip ci]"
            git push
          name: Commit to Git

jobs:
  package_and_commit:
    executor:
      name: maven/default
      tag: "21.0.0-node"
    steps:
      - maven_package
      # - install_wix
      # - create_msi
      - generate_executable
      - generate_installer
      - git_commit


workflows:
  package_and_commit:
    jobs:
      - package_and_commit