version: '2.1'
orbs:
  maven: circleci/maven@1.1

commands:
  maven_package:
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                command: |-
                  #!/bin/bash
                  
                  set -x
                  # shellcheck disable=SC2086
                  mvn clean package "$@"
                  set +x
      - maven/process_test_results
  git_commit:
    steps:
      - run:
          command: |-
            git config --global user.email "andrewhun995@gmail.com"
            git config --global user.name "Andras Tyichi"
            git branch -u origin/reset
            git add --all
            git commit -m "Pushing Packaged Content Via CircleCI [skip ci]"
            git push
  install_dotnet:
    steps:
      - run:
          command: |-
            wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
            chmod +x ./dotnet-install.sh
            ./dotnet-install.sh --version latest

jobs:
  package_and_commit:
    executor:
      name: maven/default
      tag: "21.0.0-node"
    steps:
      - maven_package
      - git_commit


workflows:
  package_and_commit:
    jobs:
      - package_and_commit