version: '2.1'
orbs:
  maven: circleci/maven@1.1

jobs:
  git_commit:
    executor: maven/default
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                command: |-
                  #!/bin/bash
                  ls
                #git add --all
                #git commit -m "Push Changes Made By Circle CI [skip ci]"
                #git push

workflows:
  maven_package:
    jobs:
      - maven/test:
          executor:
            name: maven/default
            tag: "21.0.0-node"
          command: "clean package"
      - git_commit