version: '2.1'
orbs:
  maven: circleci/maven@1.1

jobs:
  package:
    executor: maven/default
    steps:
      - run:
          name: Maven Package
          command: |
            cd /
            ls

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor:
            tag: "21.0.0-node"