version: '2.1'
orbs:
  maven: circleci/maven@1.1

jobs:
  package:
    executor: maven/default
    steps:
      - run:
          name: Maven Package
          command: |
            mvn clean package

workflows:
  maven_package:
    jobs:
      - package